const CULTIVOS_DB = [

  // ── LECHUGAS ────────────────────────────────────────────────────────────
  { id:'romana',       nombre:'Romana',           abrev:'RO', grupo:'lechugas',  emoji:'🥬',
    ecMin:800,  ecMax:1400, phMin:5.5, phMax:6.5, dias:45,
    dificultad:'fácil', sistemaIdeal:'torre,nft,dwc',
    nota:'La más productiva en hidroponía. Tolera bien el calor. Rebota tras corte.',
    fructificacion: false },
  { id:'trocadero',    nombre:'Trocadero',         abrev:'TC', grupo:'lechugas',  emoji:'🥬',
    ecMin:800,  ecMax:1400, phMin:5.5, phMax:6.5, dias:40,
    dificultad:'fácil', sistemaIdeal:'torre,nft',
    nota:'Textura mantecosa. Sensible al tipburn con baja circulación de aire.',
    fructificacion: false },
  { id:'maravilla',    nombre:'Maravilla',         abrev:'MV', grupo:'lechugas',  emoji:'🥬',
    ecMin:800,  ecMax:1200, phMin:5.5, phMax:6.5, dias:50,
    dificultad:'fácil', sistemaIdeal:'torre,nft',
    nota:'Tolerante al frío. Ideal otoño-invierno en Castelló.',
    fructificacion: false },
  { id:'lolorrosso',   nombre:'Lolo Rosso',        abrev:'LR', grupo:'lechugas',  emoji:'🥬',
    ecMin:800,  ecMax:1400, phMin:5.5, phMax:6.5, dias:45,
    dificultad:'fácil', sistemaIdeal:'torre,nft',
    nota:'Color rojizo intenso. Más resistente al calor que las verdes. Ideal verano.',
    fructificacion: false },
  { id:'hojaroble',    nombre:'Hoja Roble Rojo',   abrev:'HR', grupo:'lechugas',  emoji:'🍂',
    ecMin:800,  ecMax:1400, phMin:5.5, phMax:6.5, dias:45,
    dificultad:'fácil', sistemaIdeal:'torre,nft',
    nota:'Hojas tipo roble. Lenta pero sabrosa. Apta para verano.',
    fructificacion: false },
  { id:'batavia',      nombre:'Batavia',            abrev:'BV', grupo:'lechugas',  emoji:'🥬',
    ecMin:800,  ecMax:1400, phMin:5.5, phMax:6.5, dias:50,
    dificultad:'fácil', sistemaIdeal:'torre,nft',
    nota:'Bordes crujientes. Aguanta el calor mejor que mantecosas.',
    fructificacion: false },
  { id:'iceberg',      nombre:'Iceberg',            abrev:'IB', grupo:'lechugas',  emoji:'💚',
    ecMin:1000, ecMax:1600, phMin:5.8, phMax:6.5, dias:60,
    dificultad:'media', sistemaIdeal:'torre,nft',
    nota:'Necesita más espacio y tiempo. Requiere cestas ≥5cm. Sensible al tipburn.',
    fructificacion: false },
  { id:'mantecosa',    nombre:'Mantecosa',          abrev:'MT', grupo:'lechugas',  emoji:'🧈',
    ecMin:800,  ecMax:1200, phMin:5.5, phMax:6.5, dias:45,
    dificultad:'fácil', sistemaIdeal:'torre,nft',
    nota:'Sabor suave. Ideal invierno. Muy sensible al bolting en verano.',
    fructificacion: false },

  // ── HOJAS VERDES ─────────────────────────────────────────────────────────
  { id:'rucula',       nombre:'Rúcula',             grupo:'hojas',     emoji:'🌿',
    ecMin:1400, ecMax:1800, phMin:6.0, phMax:7.0, dias:30,
    dificultad:'fácil', sistemaIdeal:'torre,nft,aeroponia',
    nota:'Crecimiento rápido. EC más alta que lechugas. Sabor picante intenso en verano.',
    fructificacion: false },
  { id:'espinaca',     nombre:'Espinaca',           abrev:'ES', grupo:'hojas',     emoji:'🥬',
    ecMin:1800, ecMax:2300, phMin:6.0, phMax:7.0, dias:40,
    dificultad:'media', sistemaIdeal:'nft,dwc',
    nota:'EC alta — no mezclar con lechugas en mismo depósito. Prefiere frío (10-20°C).',
    fructificacion: false },
  { id:'acelga',       nombre:'Acelga',             grupo:'hojas',     emoji:'🍀',
    ecMin:1800, ecMax:2300, phMin:6.0, phMax:7.0, dias:50,
    dificultad:'fácil', sistemaIdeal:'nft,dwc',
    nota:'Muy productiva. Tolera rango amplio de temperatura. Rebrota tras corte.',
    fructificacion: false },
  { id:'col_rizada',   nombre:'Kale / Col rizada', grupo:'hojas',     emoji:'🥦',
    ecMin:1200, ecMax:1500, phMin:5.5, phMax:6.5, dias:55,
    dificultad:'fácil', sistemaIdeal:'torre,nft',
    nota:'Superalimento. Compatible con lechugas en EC. Aguanta bien el frío.',
    fructificacion: false },
  { id:'berros',       nombre:'Berros',             grupo:'hojas',     emoji:'💧',
    ecMin:400,  ecMax:1800, phMin:6.5, phMax:6.8, dias:30,
    dificultad:'fácil', sistemaIdeal:'nft,agua_corriente',
    nota:'Rango EC muy amplio. Necesita mucha agua y buena circulación.',
    fructificacion: false },
  { id:'lechuga_agua', nombre:'Lechuga de agua',   grupo:'hojas',     emoji:'🌊',
    ecMin:400,  ecMax:1200, phMin:6.0, phMax:7.0, dias:35,
    dificultad:'fácil', sistemaIdeal:'dwc,nft',
    nota:'EC baja. Sistema DWC ideal. Crece muy rápido en verano.',
    fructificacion: false },

  // ── ASIÁTICAS / MOSTAZA ───────────────────────────────────────────────────
  { id:'mizuna',       nombre:'Mizuna',             grupo:'asiaticas', emoji:'🌿',
    ecMin:1200, ecMax:1400, phMin:5.5, phMax:6.5, dias:35,
    dificultad:'fácil', sistemaIdeal:'torre,nft',
    nota:'La más fácil y productiva de las asiáticas. Compatible con lechugas.',
    fructificacion: false },
  { id:'komatsuna',    nombre:'Komatsuna',          abrev:'KM', grupo:'asiaticas', emoji:'🥬',
    ecMin:1200, ecMax:1400, phMin:6.0, phMax:7.0, dias:35,
    dificultad:'fácil', sistemaIdeal:'torre,nft',
    nota:'Sabor suave tipo espinaca. Muy productiva. Compatible con lechugas.',
    fructificacion: false },
  { id:'pak_choi',     nombre:'Pak Choi / Bok Choy',abrev:'PC', grupo:'asiaticas', emoji:'🥬',
    ecMin:1500, ecMax:2500, phMin:6.0, phMax:7.0, dias:40,
    dificultad:'media', sistemaIdeal:'nft,dwc',
    nota:'EC más alta — cuidado al mezclar con lechugas. Prefiere temperaturas frescas.',
    fructificacion: false },
  { id:'tatsoi',       nombre:'Tatsoi',             grupo:'asiaticas', emoji:'🌸',
    ecMin:1200, ecMax:1800, phMin:5.5, phMax:6.5, dias:40,
    dificultad:'fácil', sistemaIdeal:'torre,nft',
    nota:'Hojas en roseta. Muy decorativa. Tolera el frío mejor que otras asiáticas.',
    fructificacion: false },
  { id:'mostaza',      nombre:'Mostaza roja/verde', grupo:'asiaticas', emoji:'🌿',
    ecMin:1200, ecMax:2400, phMin:6.0, phMax:6.5, dias:30,
    dificultad:'fácil', sistemaIdeal:'torre,nft',
    nota:'Crecimiento muy rápido. Sabor picante. Listo para microgreens en 10 días.',
    fructificacion: false },

  // ── HIERBAS AROMÁTICAS ────────────────────────────────────────────────────
  { id:'albahaca',     nombre:'Albahaca',           grupo:'hierbas',   emoji:'🌿',
    ecMin:1000, ecMax:1600, phMin:5.5, phMax:6.0, dias:30,
    dificultad:'media', sistemaIdeal:'torre,nft,aeroponia',
    nota:'Necesita 18°C mínimo. Repele pulgones. No mezclar con menta (EC diferente).',
    fructificacion: false },
  { id:'menta',        nombre:'Menta / Hierbabuena',grupo:'hierbas',   emoji:'🍵',
    ecMin:2000, ecMax:2400, phMin:5.5, phMax:6.0, dias:30,
    dificultad:'media', sistemaIdeal:'nft,dwc',
    nota:'EC alta — no mezclar con lechugas. Invasiva, mejor en torre separada. Muy aromática.',
    fructificacion: false },
  { id:'perejil',      nombre:'Perejil',            grupo:'hierbas',   emoji:'🌱',
    ecMin:800,  ecMax:1800, phMin:5.5, phMax:6.0, dias:60,
    dificultad:'media', sistemaIdeal:'torre,nft',
    nota:'Germinación lenta. Una vez establecido, muy productivo. Compatible con lechugas.',
    fructificacion: false },
  { id:'cilantro',     nombre:'Cilantro',           grupo:'hierbas',   emoji:'🥗',
    ecMin:1200, ecMax:1800, phMin:5.8, phMax:6.4, dias:30,
    dificultad:'media', sistemaIdeal:'torre,nft',
    nota:'Se espiga rápido con calor. Mejor en otoño-primavera. Cosechar joven.',
    fructificacion: false },
  { id:'oregano',      nombre:'Orégano',            grupo:'hierbas',   emoji:'🍕',
    ecMin:1800, ecMax:2300, phMin:6.0, phMax:7.0, dias:60,
    dificultad:'media', sistemaIdeal:'nft',
    nota:'EC alta. Necesita mucha luz. Mejor secado que fresco en hidropónica.',
    fructificacion: false },
  { id:'romero',       nombre:'Romero',             grupo:'hierbas',   emoji:'🌲',
    ecMin:1000, ecMax:1600, phMin:5.5, phMax:6.0, dias:90,
    dificultad:'difícil', sistemaIdeal:'aeroponía',
    nota:'Crecimiento lento. Sensible al exceso de humedad en raíces. Aeroponía ideal.',
    fructificacion: false },
  { id:'tomillo',      nombre:'Tomillo',            grupo:'hierbas',   emoji:'🍯',
    ecMin:800,  ecMax:1600, phMin:5.5, phMax:7.0, dias:60,
    dificultad:'media', sistemaIdeal:'nft,aeroponia',
    nota:'Rango EC amplio. Tolera periodos de sequía. Buena elección para principiantes.',
    fructificacion: false },
  { id:'lavanda',      nombre:'Lavanda',            grupo:'hierbas',   emoji:'💜',
    ecMin:1000, ecMax:1400, phMin:6.4, phMax:6.8, dias:90,
    dificultad:'difícil', sistemaIdeal:'aeroponia',
    nota:'Prefiere pH más alto. Necesita periodos de menor riego. Difícil en torres.',
    fructificacion: false },
  { id:'eneldo',       nombre:'Eneldo',             grupo:'hierbas',   emoji:'🍃',
    ecMin:1000, ecMax:1600, phMin:5.5, phMax:6.4, dias:45,
    dificultad:'media', sistemaIdeal:'torre,nft',
    nota:'Se espiga rápido. Cosechar antes de florecer. Sabor anisado.',
    fructificacion: false },
  { id:'cebollino',    nombre:'Cebollino',          grupo:'hierbas',   emoji:'🧅',
    ecMin:1800, ecMax:2400, phMin:6.0, phMax:6.5, dias:30,
    dificultad:'fácil', sistemaIdeal:'torre,nft',
    nota:'EC alta — separarlos de lechugas. Se corta y rebrota varias veces.',
    fructificacion: false },

  // ── FRUTOS (REQUIEREN SISTEMA DEDICADO) ──────────────────────────────────
  { id:'tomate',       nombre:'Tomate',             grupo:'frutos',    emoji:'🍅',
    ecMin:1500, ecMax:3000, phMin:5.5, phMax:6.3, dias:90,
    dificultad:'difícil', sistemaIdeal:'dwc,nft_frutos,sustrato',
    nota:'EC aumenta según fase: veg 1500-2000, fruto 2000-3000. Necesita tutores y polinización.',
    fructificacion: true,
    fases: {
      plantula:     { ec:[800,1200],  ph:[5.8,6.2], dias:14 },
      vegetativo:   { ec:[1500,2000], ph:[5.5,6.3], dias:30 },
      floracion:    { ec:[2000,2500], ph:[5.5,6.3], dias:20 },
      fructificacion:{ ec:[2000,3000], ph:[5.8,6.5], dias:40 },
    } },
  { id:'pimiento',     nombre:'Pimiento / Capsicum',grupo:'frutos',    emoji:'🫑',
    ecMin:1800, ecMax:2200, phMin:6.0, phMax:6.5, dias:90,
    dificultad:'difícil', sistemaIdeal:'dwc,sustrato',
    nota:'Necesita temperatura 20-28°C. EC más estable que tomate. Requiere polinización.',
    fructificacion: true,
    fases: {
      plantula:     { ec:[800,1200],  ph:[5.8,6.2], dias:14 },
      vegetativo:   { ec:[1500,2000], ph:[6.0,6.5], dias:40 },
      floracion:    { ec:[2000,2500], ph:[6.0,6.5], dias:20 },
      fructificacion:{ ec:[2000,3000], ph:[6.0,6.5], dias:40 },
    } },
  { id:'pimiento_picante', nombre:'Pimiento picante / Chile', grupo:'frutos', emoji:'🌶️',
    ecMin:3000, ecMax:3500, phMin:5.0, phMax:6.5, dias:100,
    dificultad:'difícil', sistemaIdeal:'dwc,sustrato',
    nota:'EC muy alta. Sistema dedicado obligatorio. Más tolerante al estrés que el dulce.',
    fructificacion: true },
  { id:'pepino',       nombre:'Pepino',             abrev:'PP', grupo:'frutos',    emoji:'🥒',
    ecMin:1700, ecMax:2500, phMin:5.5, phMax:6.0, dias:60,
    dificultad:'media', sistemaIdeal:'nft_frutos,dwc',
    nota:'pH más bajo que otros frutos. Necesita tutores. Muy productivo en verano.',
    fructificacion: true },
  { id:'calabacin',    nombre:'Calabacín / Zucchini',abrev:'ZU', grupo:'frutos',   emoji:'🥒',
    ecMin:1800, ecMax:2400, phMin:6.0, phMax:7.0, dias:55,
    dificultad:'media', sistemaIdeal:'dwc,sustrato',
    nota:'Planta grande — necesita mucho espacio. Muy productivo. Requiere polinización.',
    fructificacion: true },

  // ── FRESAS ────────────────────────────────────────────────────────────────
  { id:'fresa',        nombre:'Fresa',              abrev:'FR', grupo:'fresas',    emoji:'🍓',
    ecMin:1800, ecMax:2200, phMin:5.5, phMax:6.5, dias:90,
    dificultad:'media', sistemaIdeal:'torre,nft,sustrato',
    nota:'Ideal en torres verticales. Producción estacional. EC aumenta en fructificación.',
    fructificacion: true,
    fases: {
      vegetativo:    { ec:[1200,1500], ph:[5.5,6.5], dias:30 },
      floracion:     { ec:[1500,1800], ph:[5.5,6.5], dias:20 },
      fructificacion:{ ec:[1800,2500], ph:[5.5,6.5], dias:40 },
    } },
  { id:'freson',       nombre:'Fresón / Albión',    abrev:'FS', grupo:'fresas',    emoji:'🍓',
    ecMin:1500, ecMax:2000, phMin:5.8, phMax:6.2, dias:90,
    dificultad:'media', sistemaIdeal:'torre,nft',
    nota:'Variedad remontante — produce todo el año. Muy popular en hidroponía vertical.',
    fructificacion: true },

  // ── RAÍCES ────────────────────────────────────────────────────────────────
  { id:'zanahoria',    nombre:'Zanahoria',          grupo:'raices',    emoji:'🥕',
    ecMin:1600, ecMax:2000, phMin:6.3, phMax:6.3, dias:75,
    dificultad:'difícil', sistemaIdeal:'aeroponia,sustrato_profundo',
    nota:'Necesita sustrato profundo (≥20cm) o aeroponía. Difícil en torres verticales estándar.',
    fructificacion: false },
  { id:'rabano',       nombre:'Rábano',             grupo:'raices',    emoji:'🤍',
    ecMin:1600, ecMax:2200, phMin:6.0, phMax:7.0, dias:25,
    dificultad:'fácil', sistemaIdeal:'aeroponia,sustrato',
    nota:'El cultivo más rápido. 25 días de semilla a cosecha. Necesita espacio para la raíz.',
    fructificacion: false },

  // ── MICROGREENS ──────────────────────────────────────────────────────────
  { id:'microgreens_mezcla', nombre:'Microgreens (mezcla)', abrev:'MG', grupo:'microgreens', emoji:'🌱',
    ecMin:800,  ecMax:1600, phMin:5.5, phMax:6.5, dias:10,
    dificultad:'fácil', sistemaIdeal:'bandeja,nft',
    nota:'Solo agua los primeros días, sin nutrientes hasta cotilédones. Cosecha en 7-14 días.',
    fructificacion: false },
  { id:'girasol_micro', nombre:'Microgreens de girasol', abrev:'GI', grupo:'microgreens', emoji:'🌻',
    ecMin:800,  ecMax:1200, phMin:5.5, phMax:6.5, dias:10,
    dificultad:'fácil', sistemaIdeal:'bandeja',
    nota:'Los más nutritivos. Sabor a nuez. Necesitan oscuridad los 3 primeros días.',
    fructificacion: false },
];
