/**
 * Catálogo de nutrientes (EC/ml, partes A+B, CalMag, etc.).
 * Carga antes de los bloques que usan NUTRIENTES_DB (setup, torre, checklist).
 */

// ══════════════════════════════════════════════════
// DATOS NUTRIENTES — Catálogo (CalMag blando: siempre ~400 µS/cm vía mlCalMagParaAguaBlanda)
// ══════════════════════════════════════════════════
const NUTRIENTES_DB = [
  {
    id: 'canna_aqua',
    nombre: 'Canna Aqua Vega A+B',
    bandera: '🇳🇱',
    partes: 2,
    buffer: true,
    sistema: 'recirculante', // NFT, DWC, ebb&flow
    ecPorMl: 33,             // reserva / fallback; cálculo principal = ml/L tabla (REF) + CalMag
    ecObjetivo: [900, 1400], // mS/cm según fabricante (0.9-1.4 con agua EC 0)
    calmagNecesario: true,
    calmagMl: 13,            // calibrado: 13ml→400µS en 18L agua destilada
    pHBuffer: true,
    pHRango: [5.2, 6.2],     // rango oficial Canna
    pHIntervenir: [5.0, 6.4],// solo intervenir fuera de este rango
    orden: ['Aqua Vega A', 'Aqua Vega B'],
    dosis: { min: 0.5, max: 2.0, unidad: 'ml/L', recomendado: 2.0 }, // 20ml/10L = 2ml/L
    protocolo: [
      '1. Llenar con agua destilada/ósmosis',
      '2. Añadir CalMag (13ml/18L) → remover 2 min',
      '3. Añadir Aqua Vega A (30ml) → remover 2 min',
      '4. Añadir Aqua Vega B (30ml) → remover 3 min',
      '5. Medir pH — estará en 3.5-4.5 (normal)',
      '6. Añadir pH+ MÍNIMO solo hasta pH 5.0',
      '7. Encender bomba — NO tocar el pH más',
      '8. Esperar 2-3h: los buffers subirán a 5.5-6.2 solos',
      '9. Medir a las 24h — intervenir solo si <5.2 o >6.4',
    ],
    detalle: 'A+B · Sistemas recirculantes · Buffer pH integrado',
    nota: '⭐ La que usas tú. Constantes calibradas con datos reales (16/03/2026).',
    precio: '€€',
    disponible_es: true,
  },
  {
    id: 'canna_substra_soft',
    nombre: 'Canna Substra Vega Soft Water',
    bandera: '🇳🇱',
    partes: 2,
    buffer: false,
    sistema: 'drain_to_waste', // riego con drenaje
    ecPorMl: 28,
    ecObjetivo: [800, 1500],
    calmagNecesario: true,
    calmagMl: 8,
    pHBuffer: false,
    pHRango: [5.5, 6.5],
    pHIntervenir: [5.5, 6.5],
    orden: ['Substra A', 'Substra B'],
    dosis: { min: 1.5, max: 4.0, unidad: 'ml/L c/u (A y B)', recomendado: 2.5 },
    protocolo: [
      '1. Llenar con agua blanda/ósmosis',
      '2. Añadir CalMag → remover',
      '3. Añadir Substra A → remover 2 min',
      '4. Añadir Substra B → remover 3 min',
      '5. Medir pH y ajustar a 5.5-6.2',
      '6. Medir EC — objetivo 0.8-1.5 mS/cm sobre el agua base',
    ],
    detalle: 'A+B · Riego con drenaje · Aguas blandas/ósmosis',
    nota: 'Para sistemas drain-to-waste (no recirculantes). Versión agua blanda.',
    precio: '€€',
    disponible_es: true,
  },
  {
    id: 'advanced_ph_perfect',
    nombre: 'Advanced Nutrients pH Perfect GMB',
    bandera: '🇨🇦',
    partes: 3,
    buffer: true,
    sistema: 'todos',
    ecPorMl: 22,
    ecObjetivo: [1200, 1800],
    calmagNecesario: false,   // incluye Ca y Mg en Micro
    calmagMl: 0,
    pHBuffer: true,           // pH Perfect — se ajusta automáticamente
    pHRango: [5.5, 6.5],
    pHIntervenir: [5.0, 7.0], // raramente necesario ajustar
    orden: ['Micro', 'Grow', 'Bloom'],
    dosis: {
      semillas: 1, plantula: 2, veg: 4, flora: 4,
      unidad: 'ml/L de cada uno',
      recomendado: 4,
    },
    protocolo: [
      '1. Llenar con agua RO (recomendado EC < 160 µS/cm)',
      '2. Añadir Micro (4ml/L) → remover bien',
      '3. Añadir Grow (4ml/L) → remover',
      '4. Añadir Bloom (4ml/L) → remover',
      '5. NO ajustar pH — la tecnología pH Perfect lo hace sola',
      '6. Verificar EC: objetivo 1.2-1.8 mS/cm',
    ],
    detalle: 'Grow+Micro+Bloom · pH automático · Sin necesidad de pH metro',
    nota: 'El sistema más caro pero elimina ajuste de pH. EC objetivo mayor que Canna.',
    precio: '€€€',
    disponible_es: true,
  },
  {
    id: 'ghe_flora',
    nombre: 'GHE Flora Series (FloraGro+Micro+Bloom)',
    bandera: '🇺🇸',
    partes: 3,
    buffer: false,
    sistema: 'todos',
    ecPorMl: 20,
    ecObjetivo: [900, 1400],  // para lechugas en veg
    calmagNecesario: true,
    calmagMl: 6,
    pHBuffer: false,
    pHRango: [5.5, 6.5],
    pHIntervenir: [5.5, 6.5],
    orden: ['FloraMicro ⚠️ primero', 'FloraGro', 'FloraBloom'],
    dosis: {
      lechugas_veg: { micro: 2.6, gro: 1.3, bloom: 1.3 }, // 1:2:1 ratio lechugas
      unidad: 'ml/L',
      recomendado: 5.2, // total ml/L
    },
    protocolo: [
      '1. Llenar con agua (pH equilibrado 5.5-6.5)',
      '2. Añadir FloraMicro PRIMERO (2.6ml/L) → remover',
      '3. Añadir FloraGro (1.3ml/L) → remover',
      '4. Añadir FloraBloom (1.3ml/L) → remover',
      '5. Esperar 10-15 min y medir EC y pH',
      '6. Ajustar pH a 5.5-6.5',
      '⚠️ NUNCA mezclar Micro directamente con Bloom',
    ],
    detalle: 'FloraGro+FloraMicro+FloraBloom · El estándar mundial · Ratio 1:2:1 para lechugas',
    nota: 'Usado por la NASA. El más estudiado del mundo. 3 botellas vs 2 de Canna. Equivalente comercial Terra Aquatica Flora Series.',
    precio: '€€',
    disponible_es: true,
  },
  {
    id: 'plagron_hydro',
    nombre: 'Plagron Hydro A+B',
    bandera: '🇳🇱',
    partes: 2,
    buffer: false,
    sistema: 'recirculante',
    ecPorMl: 23,
    ecObjetivo: [900, 1500],
    calmagNecesario: true,
    calmagMl: 5.5,
    pHBuffer: false,
    pHRango: [5.5, 6.5],
    pHIntervenir: [5.5, 6.5],
    orden: ['Hydro A', 'Hydro B'],
    dosis: { min: 1.5, max: 3.5, unidad: 'ml/L', recomendado: 2.5 },
    protocolo: [
      '1. Llenar con agua blanda/ósmosis',
      '2. Añadir CalMag → remover',
      '3. Añadir Hydro A (2.5ml/L) → remover 2 min',
      '4. Añadir Hydro B (2.5ml/L) → remover 3 min',
      '5. Ajustar pH a 5.5-6.5',
      '6. Verificar EC — objetivo 0.9-1.5 mS/cm',
    ],
    detalle: 'A+B · Alta concentración · Aguas duras y blandas',
    nota: 'Muy concentrado — menor coste por litro preparado. Popular en Europa.',
    precio: '€€',
    disponible_es: true,
  },
  {
    id: 'hesi_tnt',
    nombre: 'Hesi TNT Complex',
    bandera: '🇩🇪',
    partes: 1,
    buffer: false,
    sistema: 'todos',
    ecPorMl: 21,
    ecObjetivo: [800, 1400],
    calmagNecesario: true,
    calmagMl: 5.0,
    pHBuffer: false,
    pHRango: [5.5, 6.5],
    pHIntervenir: [5.5, 6.5],
    orden: ['TNT Complex'],
    dosis: { min: 3, max: 5, unidad: 'ml/L', recomendado: 5 },
    protocolo: [
      '1. Llenar con agua blanda',
      '2. Añadir CalMag → remover',
      '3. Añadir TNT Complex (5ml/L) → remover bien',
      '4. Ajustar pH a 5.5-6.5',
      '5. Verificar EC',
    ],
    detalle: 'Todo en 1 botella · Vitaminas + aminoácidos + micronutrientes',
    nota: 'Ideal para principiantes — una sola botella para toda la fase veg.',
    precio: '€',
    disponible_es: true,
  },
  {
    id: 'biobizz',
    nombre: 'BioBizz Fish·Mix + Alg·A·Mic',
    bandera: '🇳🇱',
    partes: 2,
    buffer: false,
    sistema: 'todos',
    ecPorMl: 18,
    ecObjetivo: [700, 1200],  // orgánico — EC más baja
    calmagNecesario: true,
    calmagMl: 6.0,
    pHBuffer: false,
    pHRango: [6.0, 7.0],      // orgánico — pH más alto
    pHIntervenir: [5.8, 7.2],
    orden: ['Fish·Mix', 'Alg·A·Mic'],
    dosis: { min: 1, max: 4, unidad: 'ml/L Fish·Mix + Alg·A·Mic aparte', recomendado: 2 },
    protocolo: [
      '1. Llenar con agua a temperatura ambiente',
      '2. Añadir Fish·Mix (2 ml/L) → remover',
      '3. Añadir Alg·A·Mic (1 ml/L) → remover',
      '4. pH objetivo más alto: 6.0-7.0 (orgánico)',
      '5. EC esperada más baja — normal en orgánico',
    ],
    detalle: 'Orgánico certificado · Pescado + algas marinas · Biopónica',
    nota: '100% orgánico. EC más baja y estable. pH objetivo diferente (6.0-7.0).',
    precio: '€€',
    disponible_es: true,
  },
  {
    id: 'campeador',
    nombre: 'Campeador Hoja A+B',
    bandera: '🇪🇸',
    partes: 2,
    buffer: false,
    sistema: 'recirculante',
    ecPorMl: 22,
    ecObjetivo: [900, 1400],
    calmagNecesario: true,
    calmagMl: 6.0,
    pHBuffer: false,
    pHRango: [5.5, 6.5],
    pHIntervenir: [5.5, 6.5],
    orden: ['Campeador A', 'Campeador B'],
    dosis: { min: 0.5, max: 2.5, unidad: 'ml/L (cada parte A y B)', recomendado: 1 },
    protocolo: [
      '1. Llenar con agua destilada/ósmosis (EC ~0)',
      '2. Añadir CalMag → remover',
      '3. Añadir Campeador A (~1 ml/L en blanda; p. ej. 18 ml en 18 L) → remover 2 min',
      '4. Añadir Campeador B (misma ml/L que A) → remover 3 min',
      '5. Ajustar pH a 5.5-6.5 según medidor',
      '6. Verificar EC objetivo y afinar según ficha del fabricante',
    ],
    detalle: 'A+B · 100% española · NPK + micronutrientes quelados',
    nota: 'Marca española de laboratorio propio. Excelente relación calidad/precio.',
    precio: '€',
    disponible_es: true,
  },
  {
    id: 'canna_hydro_vega',
    nombre: 'Canna Hydro Vega A+B',
    bandera: '🇳🇱',
    partes: 2,
    buffer: false,
    sistema: 'drain_to_waste',
    ecPorMl: 28,
    ecObjetivo: [1000, 1800],
    calmagNecesario: true,
    calmagMl: 13,
    pHBuffer: false,
    pHRango: [5.2, 6.2],
    pHIntervenir: [5.0, 6.4],
    orden: ['Hydro Vega A', 'Hydro Vega B'],
    dosis: { min: 2, max: 5, unidad: 'ml/L c/u', recomendado: 4 },
    protocolo: [
      '1. Agua destilada/ósmosis',
      '2. Opción CalMag hasta ~400 µS/cm → remover',
      '3. Añadir Hydro Vega A → B (no mezclar concentrados)',
      '4. pH y EC según ficha Canna Hydro',
    ],
    detalle: 'A+B · Riego run-to-waste · Inerte',
    nota: 'Más concentrada que Aqua en muchas tablas; hidro clásico Canna.',
    precio: '€€',
    disponible_es: true,
  },
  {
    id: 'atami_bcuzz_hydro',
    nombre: "Atami B'cuzz Hydro A+B",
    bandera: '🇳🇱',
    partes: 2,
    buffer: false,
    sistema: 'recirculante',
    ecPorMl: 24,
    ecObjetivo: [1000, 1600],
    calmagNecesario: true,
    calmagMl: 13,
    pHBuffer: false,
    pHRango: [5.5, 6.0],
    pHIntervenir: [5.2, 6.5],
    orden: ['B\'cuzz Hydro A', 'B\'cuzz Hydro B'],
    dosis: { min: 1, max: 3, unidad: 'ml/L c/u', recomendado: 2 },
    protocolo: [
      '1. Agua blanda',
      '2. CalMag opcional hasta ~400 µS/cm',
      '3. A en agua, remover; luego B',
      '4. pH 5,5–5,8 orientativo Atami',
    ],
    detalle: 'A+B · Atami · Hidro recirculante / inerte',
    nota: 'Rango fabricante suele ser 1–3 ml/L por parte.',
    precio: '€€',
    disponible_es: true,
  },
  {
    id: 'hypro_hydro_ab',
    nombre: 'Hy-Pro Hydro A+B',
    bandera: '🇳🇱',
    partes: 2,
    buffer: false,
    sistema: 'todos',
    ecPorMl: 23,
    ecObjetivo: [900, 1500],
    calmagNecesario: true,
    calmagMl: 13,
    pHBuffer: false,
    pHRango: [5.5, 6.5],
    pHIntervenir: [5.3, 6.7],
    orden: ['Hy-Pro A', 'Hy-Pro B'],
    dosis: { min: 1.5, max: 3.5, unidad: 'ml/L c/u', recomendado: 2.5 },
    protocolo: [
      '1. Completar con agua blanda',
      '2. CalMag hasta ~400 µS/cm si procede',
      '3. A y B en orden; no concentrado puro',
      '4. Medir EC/pH',
    ],
    detalle: 'A+B · Hy-Pro · Hidropónico',
    nota: 'Tabla app: ~2,5 ml/L por parte vegetativo.',
    precio: '€€',
    disponible_es: true,
  },
  {
    id: 'vitalink_hydro_max',
    nombre: 'VitaLink Hydro Max Grow A+B',
    bandera: '🇬🇧',
    partes: 2,
    buffer: false,
    sistema: 'todos',
    ecPorMl: 22,
    ecObjetivo: [900, 1500],
    calmagNecesario: true,
    calmagMl: 13,
    pHBuffer: false,
    pHRango: [5.5, 6.5],
    pHIntervenir: [5.2, 6.6],
    orden: ['Hydro Max A', 'Hydro Max B'],
    dosis: { min: 2, max: 4, unidad: 'ml/L c/u', recomendado: 3 },
    protocolo: [
      '1. Agua blanda',
      '2. CalMag opcional ~400 µS/cm',
      '3. A, luego B',
      '4. Ajustar pH',
    ],
    detalle: 'A+B · VitaLink Max · Crecimiento',
    nota: 'Hidro Max vegetativo: orientación ~3 ml/L A y B.',
    precio: '€€',
    disponible_es: true,
  },
  {
    id: 'mills_basis_ab',
    nombre: 'Mills Basis A/B',
    bandera: '🇳🇱',
    partes: 2,
    buffer: false,
    sistema: 'todos',
    ecPorMl: 24,
    ecObjetivo: [1000, 1600],
    calmagNecesario: true,
    calmagMl: 13,
    pHBuffer: false,
    pHRango: [5.5, 6.3],
    pHIntervenir: [5.2, 6.5],
    orden: ['Basis A', 'Basis B'],
    dosis: { min: 1, max: 4, unidad: 'ml/L c/u (A y B iguales)', recomendado: 2 },
    protocolo: [
      '1. Agua RO/blanda',
      '2. CalMag a ~400 µS/cm',
      '3. Basis A y B: mismas ml/L cada una (1 ml/L c/u ~2 primeras semanas; luego 2 ml/L c/u en veg)',
      '4. Subir según carta Mills en floración',
    ],
    detalle: 'A+B · Mills · Base mineral',
    nota: 'Mills: igual ml en A y B. Plántulas: mitad de dosis veg en tabla.',
    precio: '€€€',
    disponible_es: true,
  },
  {
    id: 'green_planet_hydro_fuel',
    nombre: 'Green Planet Hydro Fuel Grow A/B',
    bandera: '🇨🇦',
    partes: 2,
    buffer: false,
    sistema: 'todos',
    ecPorMl: 24,
    ecObjetivo: [1000, 1550],
    calmagNecesario: true,
    calmagMl: 13,
    pHBuffer: false,
    pHRango: [5.5, 6.5],
    pHIntervenir: [5.2, 6.6],
    orden: ['Hydro Fuel Grow A', 'Hydro Fuel Grow B'],
    dosis: { min: 1, max: 3.5, unidad: 'ml/L c/u (A y B)', recomendado: 2 },
    protocolo: [
      '1. Agua blanda',
      '2. CalMag ~400 µS/cm',
      '3. Parte A, remover; luego parte B (misma filosofía ml/L por botella)',
      '4. En pleno veg el fabricante llega a ~3 ml/L de A y ~3 ml/L de B',
    ],
    detalle: 'A+B · Green Planet · Grow',
    nota: 'Hydro Fuel: 1–3 ml/L por parte A y por parte B; app usa ~2 ml/L c/u en veg.',
    precio: '€€',
    disponible_es: true,
  },
  {
    id: 'ionic_grow_hydro',
    nombre: 'Ionic Grow Hydro',
    bandera: '🇬🇧',
    partes: 1,
    buffer: false,
    sistema: 'todos',
    ecPorMl: 22,
    ecObjetivo: [900, 1400],
    calmagNecesario: true,
    calmagMl: 13,
    pHBuffer: false,
    pHRango: [5.5, 6.2],
    pHIntervenir: [5.3, 6.5],
    orden: ['Ionic Grow'],
    dosis: { min: 2, max: 6, unidad: 'ml/L', recomendado: 4 },
    protocolo: [
      '1. Una sola botella (1 parte)',
      '2. CalMag blando a ~400 µS/cm',
      '3. Ionic Grow según envase',
      '4. pH estable',
    ],
    detalle: '1 parte · Ionic · Grow hw',
    nota: 'Mineral una botella; EC según cultivo.',
    precio: '€€',
    disponible_es: true,
  },
  {
    id: 'biobizz_bio_grow',
    nombre: 'BioBizz Bio-Grow',
    bandera: '🇳🇱',
    partes: 1,
    buffer: false,
    sistema: 'todos',
    ecPorMl: 20,
    ecObjetivo: [700, 1100],
    calmagNecesario: true,
    calmagMl: 13,
    pHBuffer: false,
    pHRango: [6.0, 7.0],
    pHIntervenir: [5.8, 7.2],
    orden: ['Bio-Grow'],
    dosis: { min: 2, max: 5, unidad: 'ml/L', recomendado: 3 },
    protocolo: [
      '1. Orgánico — EC más baja',
      '2. CalMag en blanda hasta ~400 µS/cm',
      '3. Bio-Grow según tabla',
      '4. pH algo más alto',
    ],
    detalle: '1 parte · Orgánico · NPK suave',
    nota: 'Distinto de Fish·Mix+Alg; solo Bio-Grow en esta entrada.',
    precio: '€€',
    disponible_es: true,
  },
  {
    id: 'hesi_hidro',
    nombre: 'Hesi Hidro Crecimiento',
    bandera: '🇩🇪',
    partes: 1,
    buffer: false,
    sistema: 'todos',
    ecPorMl: 22,
    ecObjetivo: [900, 1500],
    calmagNecesario: true,
    calmagMl: 13,
    pHBuffer: false,
    pHRango: [5.5, 6.5],
    pHIntervenir: [5.2, 6.5],
    orden: ['Hidro Crecimiento'],
    dosis: { min: 3, max: 6, unidad: 'ml/L', recomendado: 4.5 },
    protocolo: [
      '1. Agua blanda',
      '2. CalMag ~400 µS/cm',
      '3. Hesi Hidro según vegetación',
      '4. pH 5,5–6,5',
    ],
    detalle: '1 parte · línea Hidro Hesi',
    nota: 'Distinto de TNT Complex; más N para hidro.',
    precio: '€€',
    disponible_es: true,
  },
  {
    id: 'hortalan',
    nombre: 'Hortalan Solución nutritiva',
    bandera: '🇪🇸',
    partes: 1,
    buffer: false,
    sistema: 'todos',
    ecPorMl: 21,
    ecObjetivo: [900, 1400],
    calmagNecesario: true,
    calmagMl: 13,
    pHBuffer: false,
    pHRango: [5.5, 6.5],
    pHIntervenir: [5.3, 6.5],
    orden: ['Hortalan'],
    dosis: { min: 3, max: 6, unidad: 'ml/L', recomendado: 4 },
    protocolo: [
      '1. Seguir envase Hortalan',
      '2. CalMag blando ~400 µS/cm',
      '3. Mezclar y medir',
    ],
    detalle: '1 parte · Marca española',
    nota: 'Dosis orientativa; confirmar en envase.',
    precio: '€',
    disponible_es: true,
  },
  {
    id: 'fox_farm_grow_big',
    nombre: 'Fox Farm Grow Big (Trio)',
    bandera: '🇺🇸',
    partes: 1,
    buffer: false,
    sistema: 'todos',
    ecPorMl: 20,
    ecObjetivo: [1000, 1600],
    calmagNecesario: true,
    calmagMl: 13,
    pHBuffer: false,
    pHRango: [5.5, 6.5],
    pHIntervenir: [5.2, 6.8],
    orden: ['Grow Big'],
    dosis: { min: 2, max: 5, unidad: 'ml/L', recomendado: 3 },
    protocolo: [
      '1. Trio Fox Farm o solo Grow Big',
      '2. CalMag ~400 µS en blanda',
      '3. Dosis conservadora; subir si EC baja',
    ],
    detalle: '1 parte · Fox Farm · Veg',
    nota: 'ML/gal alto: app usa ~3 ml/L orientativo.',
    precio: '€€€',
    disponible_es: true,
  },
  {
    id: 'campeador_hidro',
    nombre: 'Campeador Hidro A+B',
    bandera: '🇪🇸',
    partes: 2,
    buffer: false,
    sistema: 'recirculante',
    ecPorMl: 22,
    ecObjetivo: [900, 1400],
    calmagNecesario: true,
    calmagMl: 13,
    pHBuffer: false,
    pHRango: [5.5, 6.5],
    pHIntervenir: [5.3, 6.6],
    orden: ['Campeador Hidro A', 'Campeador Hidro B'],
    dosis: { min: 1, max: 3, unidad: 'ml/L c/u', recomendado: 1 },
    protocolo: [
      '1. Ficha Hidro: 1–3 ml/L por parte A y B (no confundir con línea Hoja)',
      '2. CalMag ~400 µS/cm en blanda',
      '3. Ej. 18 L · EC ~1100–1200 µS: ~18 ml A + 18 ml B (≈1 ml/L c/u)',
    ],
    detalle: 'A+B · Campeador · Hidro',
    nota: 'Linea aparte de Campeador Hoja.',
    precio: '€',
    disponible_es: true,
  },
  {
    id: 'masterblend_41838',
    nombre: 'Masterblend 4-18-38 (polvo)',
    bandera: '🇺🇸',
    partes: 1,
    tipoDosis: 'polvo',
    buffer: false,
    sistema: 'todos',
    ecPorMl: 18,
    ecObjetivo: [1000, 2200],
    calmagNecesario: true,
    calmagMl: 13,
    pHBuffer: false,
    pHRango: [5.5, 6.5],
    pHIntervenir: [5.2, 6.8],
    orden: ['Mezcla sales (receta)'],
    dosis: { min: 1.6, max: 2.4, unidad: 'g/L total sales', recomendado: 1.9 },
    protocolo: [
      '1. Polvo: usar gramos y agua blanda',
      '2. CalMag o Epsom según receta Masterblend',
      '3. Chequear EC tras disolver (no usar solo ml de líquido)',
    ],
    detalle: '1 componente base sal · Receta típica 2-parte',
    nota: 'En la app la tabla muestra gramos por litro orientativos.',
    precio: '€',
    disponible_es: true,
  },
  {
    id: 'otro',
    nombre: 'Otra marca',
    bandera: '🔬',
    partes: 2,
    buffer: false,
    sistema: 'todos',
    ecPorMl: 25,
    ecObjetivo: [900, 1400],
    calmagNecesario: true,
    calmagMl: 6,
    pHBuffer: false,
    pHRango: [5.5, 6.5],
    pHIntervenir: [5.5, 6.5],
    orden: ['Parte A', 'Parte B'],
    dosis: { min: 1, max: 4, unidad: 'ml/L', recomendado: 2 },
    protocolo: [
      'Seguir las instrucciones del fabricante',
      'Siempre: A primero, luego B, nunca mezclar concentrados',
      'Verificar EC y ajustar pH tras mezclar',
    ],
    detalle: 'Configura manualmente tus constantes',
    nota: 'Usaremos valores estándar. Ajusta ecPorMl según tus mediciones reales.',
    precio: '?',
    disponible_es: true,
  },
];

